services:
  - type: web
    name: multiapp-dash
    env: python
    # Añade esta línea para especificar la versión de Python
    pythonVersion: 3.10.13 # O 3.11.9, etc. Recomiendo 3.10.x o 3.11.x
    plan: free
    buildCommand: ""
    startCommand: gunicorn multi_app:application
